drone:
  mass: 1.5
  arm_length: 0.225
  inertia_xx: 0.0347563
  inertia_yy: 0.0458929
  inertia_zz: 0.0977
  motor_constant: 8.54858e-06
  moment_constant: 0.016
  max_rpm: 12000
  min_rpm: 1200
  motor_time_constant: 0.02
  drag_coefficient_xy: 0.25
  drag_coefficient_z: 0.35
  propeller_radius: 0.12
simulation:
  dt: 0.001
  realtime_factor: 1.0
  max_simulation_time: 3600
  gravity: 9.81
  air_density: 1.225
visualization:
  window_width: 1400
  window_height: 900
  fps_target: 60
  camera_fov: 60.0
  grid_size: 100.0
  grid_spacing: 1.0
  trail_length: 500
  trail_color: !!python/tuple
  - 0.2
  - 0.6
  - 1.0
  - 0.8
control:
  position_kp: !!python/tuple
  - 2.0
  - 2.0
  - 4.0
  position_ki: !!python/tuple
  - 0.0
  - 0.0
  - 0.2
  position_kd: !!python/tuple
  - 1.5
  - 1.5
  - 2.0
  attitude_kp: !!python/tuple
  - 8.0
  - 8.0
  - 4.0
  attitude_ki: !!python/tuple
  - 0.0
  - 0.0
  - 0.0
  attitude_kd: !!python/tuple
  - 3.5
  - 3.5
  - 1.5
  max_velocity: 10.0
  max_acceleration: 5.0
  max_tilt_angle: 0.5
  max_yaw_rate: 2.0
